### ISSUE TITLE
EcoMath.jl Roadmap

### ISSUE THREAD

**Issue by pujaltes** [pujaltes/EcoMath.jl#1]
A roadmap of things to be done for EcoMath.jl

## Core Julia
- [ ] Create simple ReadMe with basic introduction.
- [ ] Support clustering of species based on how they interact with the ecosystem.
- [ ] Improve notebook by expanding on mathematical foundations of Turing's MCMC estimation of parameters.
- [ ] Create seperate plotting module for plotting models in graph form and plotting coexistence.
- [ ] Add functions to provide summary of ecosystem to the user (whether it will coexist, niche ratio etc.)

## Interactive Javascript
- [ ] Finish interactive coexistence figure.
- [ ] Create interactive Competitive Lotka-Voltera model with [odex](http://blog.littleredcomputer.net/math/odex/js/2016/04/03/lotka-volterra.html).
